# Generated by Django 6.0.2 on 2026-07-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="skill_type",
            field=models.CharField(
                choices=[("HAVE", "Have"), ("WANT", "Want")],
                default="HAVE",
                max_length=10,
            ),
        ),
    ]
